---
# - import_playbook: database.yml
#- import_playbook: docker.yml
- import_playbook: common.yml
- import_playbook: load_balancer.yml
- import_playbook: database.yml
- import_playbook: rancher.yml
- import_playbook: gen3.yml


